+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Fri Apr 28 21:27:11 2023 - INFO  - Start environment preparation.
+ old_lang=en_US.UTF-8
+ export LANG=en_US.utf-8
+ LANG=en_US.utf-8
++ date +%Y%m%d%H%M%S
+ cur_date=20230428212711
+ dir=testDir20230428212711
+ file=testFile20230428212711
+ mkdir /tmp/testDir20230428212711
+ touch /tmp/testDir20230428212711/testFile20230428212711
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Fri Apr 28 21:27:12 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Apr 28 21:27:13 2023 - INFO  - Start to run test.
+ soft_link=testSoft20230428212711
+ ln -s /tmp/testDir20230428212711 /tmp/testSoft20230428212711
++ stat /tmp/testDir20230428212711
++ grep Inode
++ cut -d : -f 3
++ awk '{print $1}'
+ inode1=3224
++ grep Inode
++ stat /tmp/testSoft20230428212711
++ cut -d : -f 3
++ awk '{print $1}'
+ inode2=3226
+ [[ 3224 -ne 3226 ]]
+ CHECK_RESULT 0 0 0 'Check inode failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check inode failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ls /tmp/testSoft20230428212711
+ grep testFile20230428212711
testFile20230428212711
+ CHECK_RESULT 0 0 0 'The sort link directory has some errors.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The sort link directory has some errors.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Apr 28 21:27:14 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Fri Apr 28 21:27:15 2023 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Apr 28 21:27:16 2023 - INFO  - Start to restore the test environment.
+ rm -rf /tmp/testSoft20230428212711 /tmp/testDir20230428212711
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Apr 28 21:27:17 2023 - INFO  - End to restore the test environment.
