+ source ../comm_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ tar -xf tmp_test.tar
tar: tmp_test.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
++ pushd ../
~/mugen/testcases/embedded-test/third_party_packages_test ~/mugen/testcases/embedded-test/third_party_packages_test/oe_test_pam_test_001
++ [[ -z '' ]]
+++ pwd
++ CUR=/root/mugen/testcases/embedded-test/third_party_packages_test
++ tar -xf dejagnu.tar
tar: dejagnu.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
++ RUNTEST=/root/mugen/testcases/embedded-test/third_party_packages_test/dejagnu/bin/runtest
++ chmod +x /root/mugen/testcases/embedded-test/third_party_packages_test/dejagnu/bin/runtest
chmod: cannot access '/root/mugen/testcases/embedded-test/third_party_packages_test/dejagnu/bin/runtest': No such file or directory
++ export RUNTEST
++ popd
~/mugen/testcases/embedded-test/third_party_packages_test/oe_test_pam_test_001
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Sat Apr 29 03:32:28 2023 - INFO  - Start to prepare the test environment.
+++ dirname oe_test_pam_test_001.sh
++ cd .
++ pwd
+ nowdir=/root/mugen/testcases/embedded-test/third_party_packages_test/oe_test_pam_test_001
+ export srcdir=/root/mugen/testcases/embedded-test/third_party_packages_test/oe_test_pam_test_001
+ srcdir=/root/mugen/testcases/embedded-test/third_party_packages_test/oe_test_pam_test_001
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Sat Apr 29 03:32:29 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Sat Apr 29 03:32:29 2023 - INFO  - Start to run test.
+ pushd ./tmp_test/tests
oe_test_pam_test_001.sh: line 37: pushd: ./tmp_test/tests: No such file or directory
+ chmod 777 ./Makefile ./oe_test_pam_test_001.sh
++ find ./ -name '*.c'
++ sort
+ runList=
+ failTitles=("XPASS" "ERROR" "FAIL")
+ popd
oe_test_pam_test_001.sh: line 58: popd: directory stack empty
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Sat Apr 29 03:32:30 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Sat Apr 29 03:32:32 2023 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Sat Apr 29 03:32:32 2023 - INFO  - Start to restore the test environment.
+ export srcdir=
+ srcdir=
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Sat Apr 29 03:32:33 2023 - INFO  - End to restore the test environment.
